#!/bin/bash

# SovereignStack OSS — full stack as containers (docker compose)
#
# Brings up all four OSS services in containers via the workspace
# docker-compose.yml: policy (8888), discovery (8889), metrics-proxy (8890),
# and gateway (8001). Optionally adds the monitoring stack. Seeds a demo
# user inside the policy container so its API key is usable through the
# gateway. Prints a banner with every endpoint.
#
# This is the container-mode counterpart to scripts/start-stack.sh
# (which runs the same services natively without Docker).
#
# Usage:
#   ./scripts/start-stack-docker.sh                 # all four services
#   ./scripts/start-stack-docker.sh --with-monitoring   # also Prometheus + Grafana
#   ./scripts/start-stack-docker.sh --no-seed       # don't (re-)create the demo user
#   ./scripts/start-stack-docker.sh --build         # force docker image rebuild
#   ./scripts/start-stack-docker.sh --stop          # stop running services (state preserved)
#   ./scripts/start-stack-docker.sh --down          # stop AND remove containers (full teardown)
#   ./scripts/start-stack-docker.sh --help

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Order matters: policy first (so we can seed before gateway loads keys.json),
# then discovery (gateway depends on it for the running-models registry),
# then metrics-proxy, then gateway.
MGMT_SERVICES=("policy" "discovery" "metrics-proxy")
ALL_SERVICES=("policy" "discovery" "metrics-proxy" "gateway")
MONITOR_SERVICES=("prometheus" "grafana" "node-exporter" "cadvisor")

DEMO_USER="${DEMO_USER:-demo}"
DEMO_MODEL_ALLOW="${DEMO_MODEL_ALLOW:-*}"
DAILY_QUOTA="${DAILY_QUOTA:-500000}"
MONTHLY_QUOTA="${MONTHLY_QUOTA:-10000000}"

WITH_MONITORING=false
SKIP_SEED=false
FORCE_BUILD=false
ACTION="up"   # up | stop | down

# ─── Colors / logging ─────────────────────────────────────────────────────────
BLUE='\033[1;36m'; GREEN='\033[1;32m'; YELLOW='\033[1;33m'; RED='\033[1;31m'; NC='\033[0m'
log()  { printf "${BLUE}[docker-stack]${NC} %s\n" "$*"; }
ok()   { printf "${GREEN}[ ok  ]${NC} %s\n" "$*"; }
warn() { printf "${YELLOW}[warn]${NC} %s\n" "$*"; }
die()  { printf "${RED}[fail]${NC} %s\n" "$*"; exit 1; }

show_help() {
  sed -n '3,21p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

# ─── Args ─────────────────────────────────────────────────────────────────────
for arg in "$@"; do
  case "$arg" in
    --with-monitoring) WITH_MONITORING=true ;;
    --no-seed)         SKIP_SEED=true ;;
    --build)           FORCE_BUILD=true ;;
    --stop)            ACTION="stop" ;;
    --down)            ACTION="down" ;;
    -h|--help)         show_help; exit 0 ;;
    *)                 echo "unknown arg: $arg"; show_help; exit 1 ;;
  esac
done

cd "$PROJECT_ROOT"

# ─── Preflight ────────────────────────────────────────────────────────────────
command -v docker >/dev/null || die "docker required"
docker compose version >/dev/null 2>&1 || die "docker compose plugin required (try: docker-compose if older)"

# ─── --stop / --down: tear down without bringing anything up ─────────────────
if [ "$ACTION" = "stop" ]; then
  log "stopping all OSS services (state preserved)"
  docker compose stop "${ALL_SERVICES[@]}" 2>&1 | sed 's/^/  /'
  if [ "$WITH_MONITORING" = true ]; then
    docker compose stop "${MONITOR_SERVICES[@]}" 2>&1 | sed 's/^/  /'
  fi
  ok "stopped"
  exit 0
fi

if [ "$ACTION" = "down" ]; then
  log "removing containers (state lost — volumes for prom/grafana persist)"
  docker compose down --remove-orphans 2>&1 | sed 's/^/  /'
  ok "down"
  exit 0
fi

# ─── Bring services up ────────────────────────────────────────────────────────
if [ "$FORCE_BUILD" = true ]; then
  log "rebuilding sovereignstack image (--build)"
  # Only the policy service has a `build:` section in docker-compose.yml;
  # the other three reuse the same `sovereignstack:latest` image.
  COMPOSE_BAKE=false docker compose build policy
fi

# Run containers as the host user so files written into the bind-mounted
# ~/.sovereignstack (keys.json, audit DB) end up host-owned, not root.
# Discovery + metrics-proxy still need read access to /var/run/docker.sock;
# pass through the host's docker group GID so they can talk to the daemon
# as a non-root user. Falls back gracefully if docker group doesn't exist.
export USER_UID="$(id -u)"
export USER_GID="$(id -g)"
DOCKER_GID="$(getent group docker 2>/dev/null | cut -d: -f3)"
export DOCKER_GID="${DOCKER_GID:-${USER_GID}}"

# Persist the values into .env so subsequent direct `docker compose ...`
# invocations (without going through this script) pick up the same
# host-specific UIDs/GIDs instead of the conservative compose defaults.
ENV_FILE="$PROJECT_ROOT/.env"
if [ ! -f "$ENV_FILE" ] || ! grep -q '^USER_UID=' "$ENV_FILE" 2>/dev/null; then
  {
    echo "# Auto-generated by scripts/start-stack-docker.sh — host UIDs/GIDs"
    echo "# for the docker-compose user mapping. Re-generated on every run."
    echo "USER_UID=$USER_UID"
    echo "USER_GID=$USER_GID"
    echo "DOCKER_GID=$DOCKER_GID"
  } > "$ENV_FILE"
  log "wrote $ENV_FILE for compose env (USER_UID=$USER_UID DOCKER_GID=$DOCKER_GID)"
else
  # Refresh the lines we own; preserve any other entries the user added.
  tmp="$(mktemp)"
  grep -v -E '^(USER_UID|USER_GID|DOCKER_GID)=' "$ENV_FILE" > "$tmp" || true
  {
    cat "$tmp"
    echo "USER_UID=$USER_UID"
    echo "USER_GID=$USER_GID"
    echo "DOCKER_GID=$DOCKER_GID"
  } > "$ENV_FILE"
  rm -f "$tmp"
fi

# Detect a stale root-owned keystore from a prior compose run that
# predated the host-user fix; the host can't read it, and seeding will
# fail inside the now-non-root container too. Surface a clean recovery.
KEYS_FILE="$HOME/.sovereignstack/keys.json"
if [ -f "$KEYS_FILE" ] && [ ! -r "$KEYS_FILE" ]; then
  warn "$KEYS_FILE is not readable by you (likely root-owned from a prior compose run)"
  echo "  Recover with:"
  echo "    sudo chown -R \"$USER_UID:$USER_GID\" \"$HOME/.sovereignstack\""
  echo "  Then re-run this script."
  die "stale keystore ownership — recover and retry"
fi

# Step 1 — bring up the three management-side services (policy, discovery,
# metrics-proxy) FIRST so we can seed the demo user via the policy
# container before the gateway loads keys.json. Order matters: the
# gateway loads keys.json once at startup, so any user we add after the
# gateway starts is invisible to it.
log "starting management-side services: ${MGMT_SERVICES[*]}"
docker compose up -d "${MGMT_SERVICES[@]}"

wait_healthy() {
  local svc="$1" tries=30
  local state=""
  printf "${BLUE}[docker-stack]${NC} waiting for %s to be healthy " "$svc"
  while [ "$tries" -gt 0 ]; do
    state="$(docker compose ps --format json "$svc" 2>/dev/null \
             | python3 -c 'import sys,json
try:
    d=json.loads(sys.stdin.read() or "{}")
    print(d.get("Health","unknown"))
except Exception:
    print("unknown")' 2>/dev/null)"
    if [ "$state" = "healthy" ]; then
      printf " done\n"
      ok "$svc healthy"
      return 0
    fi
    printf "."
    tries=$((tries-1))
    sleep 1
  done
  printf "\n"
  warn "$svc not healthy after 30s — continuing; check 'docker compose logs $svc'"
  return 1
}
for svc in "${MGMT_SERVICES[@]}"; do
  wait_healthy "$svc"
done

# Step 2 — seed the demo user (so the gateway sees it on first load).
# Policy is the service that owns keys.json, so seed via that container.
DEMO_KEY=""
if [ "$SKIP_SEED" = true ]; then
  log "skipping demo user seed (--no-seed)"
else
  log "seeding demo user '$DEMO_USER' inside the policy container"
  docker compose exec -T policy /app/sovstack keys remove "$DEMO_USER" >/dev/null 2>&1 || true
  ADD_OUT="$(docker compose exec -T policy /app/sovstack keys add "$DEMO_USER" \
                --department demo --team demo --role analyst 2>&1 || true)"
  echo "$ADD_OUT" | grep -E '^\s*(API Key|User ID):' || true
  DEMO_KEY="$(echo "$ADD_OUT" | awk '/API Key:/ {print $3; exit}')"
  if [ -z "$DEMO_KEY" ]; then
    warn "could not capture demo key; check 'docker compose logs policy'"
  fi
  docker compose exec -T policy /app/sovstack keys grant-model "$DEMO_USER" "$DEMO_MODEL_ALLOW" >/dev/null 2>&1 \
    || warn "grant-model failed (model whitelist may be empty)"
  docker compose exec -T policy /app/sovstack keys set-quota "$DEMO_USER" \
      --daily "$DAILY_QUOTA" --monthly "$MONTHLY_QUOTA" >/dev/null 2>&1 \
    || warn "set-quota failed"
  ok "demo user ready"
fi

# Step 3 — bring up the gateway (now keys.json contains the demo user)
# and any monitoring services the user asked for.
SERVICES=("gateway")
if [ "$WITH_MONITORING" = true ]; then
  SERVICES+=("${MONITOR_SERVICES[@]}")
fi
log "starting ${SERVICES[*]}"
docker compose up -d "${SERVICES[@]}"
wait_healthy gateway

# ─── Banner ───────────────────────────────────────────────────────────────────
cat <<EOF

──────────────────────────────────────────────────────────────────────
  SovereignStack OSS is running in containers
──────────────────────────────────────────────────────────────────────

  Gateway              http://localhost:8001
    /healthz             liveness probe
    /readyz              readiness probe (checks discovery reachable)
    /metrics             Prometheus exposition
    /v1/...              OpenAI-compatible proxy
    /api/v1/audit/logs   recent audit records (admin)

  Policy               http://localhost:8888
    /api/v1/users                   list users (admin)
    /api/v1/users/{id}/quota        update quota (PATCH, admin)
    /api/v1/access/check            pre-flight access check

  Discovery            http://localhost:8889
    /api/v1/models/running          inventory of running model containers

  Metrics-proxy        http://localhost:8890
    /api/v1/models/{name}/metrics   proxied vLLM Prometheus metrics
EOF

if [ "$WITH_MONITORING" = true ]; then
  cat <<EOF

  Monitoring (containers)
    Prometheus           http://localhost:9090
    Grafana              http://localhost:3001  (admin / admin)
    node-exporter        http://localhost:9100/metrics
    cAdvisor             http://localhost:8080
EOF
fi

if [ -n "$DEMO_KEY" ]; then
  cat <<EOF

  Demo user              $DEMO_USER
  Demo API key           $DEMO_KEY
EOF
fi

cat <<EOF

  Containers             docker compose ps
  Logs                   docker compose logs -f policy discovery metrics-proxy gateway
  Stop (preserve state)  ./scripts/start-stack-docker.sh --stop
  Tear down completely   ./scripts/start-stack-docker.sh --down

  Try it:
    # Routing path: /models/<name>/v1/...  (NOT /v1/models/<name>/...)
EOF

if [ -n "$DEMO_KEY" ]; then
cat <<EOF
    curl -H "X-API-Key: $DEMO_KEY" \\
         -H "Content-Type: application/json" \\
         -d '{"messages":[{"role":"user","content":"hi"}]}' \\
         http://localhost:8001/models/<deployed-model-name>/v1/chat/completions
EOF
fi

cat <<EOF
──────────────────────────────────────────────────────────────────────
EOF
